version: 2.1
jobs:
  build:
    docker:
      - image: cimg/java:3.10.1
      - image: cimg/base:stable
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            node.js -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            html main.html
      - store_artifacts:
          path: hawkhacks/
          destination: circle_ci
